name: Triton
main: com.rexcantor64.triton.plugin.SpigotPlugin
version: 1.3.0
website: https://triton.rexcantor64.com/
author: Rexcantor64
depend: [ProtocolLib]
softdepend: [PlaceholderAPI]
description: A plugin that replaces any message on your server, to the receiver's language, in real time!
commands:
  triton:
    aliases: [mlp, ml, multilanguage, language, lang, multilanguageplugin]
    description: The main command of Triton. For compatibility reasons, /mlp and all its aliases still work.
  twin:
    description: Upload and download your config to/from the Triton Web INterface
    usage: /twin [code]
    aliases: [tritonweb, tweb, twebinterface, tritonwebinterface]
permissions:
  triton.getflag:
    default: op
  triton.setlanguage:
    default: true
  triton.setlanguage.others:
    default: op
  triton.openselector:
    default: true
  triton.reload:
    default: op
  triton.help:
    default: true
  triton.sign:
    default: op
  twin.upload:
    default: op
  twin.download:
    default: op