name: Triton
main: com.rexcantor64.triton.plugin.SpigotPlugin
version: 1.0.0-BETA_3
website: https://www.spigotmc.org/resources/triton.30331/
author: Rexcantor64
depend: [ProtocolLib]
description: A plugin that replaces any message on your server, to the receiver's language, in real time!
commands:
    triton:
        aliases: [mlp, ml, multilanguage, language, lang, multilanguageplugin]
        description: The main command of Triton. For compatibility reasons, /mlp and all its aliases still work.
    twin:
        description: Upload and download your config to/from the Triton Web INterface
        usage: /twin [code]
        aliases: [tritonweb, tweb, twebinterface, tritonwebinterface]
permissions:
    multilanguageplugin.getflag:
        default: op
    multilanguageplugin.setlanguage:
        default: true
    multilanguageplugin.setlanguage.others:
        default: op
    multilanguageplugin.openselector:
        default: true
    multilanguageplugin.reload:
        default: op
    multilanguageplugin.help:
        default: true
    twin.upload:
        default: op
    twin.download:
        default: op
