name: MLPTestSuite
main: com.rexcantor64.triton.testsuite.Main
version: 0.0.1
website: https://www.spigotmc.org/resources/triton.30331/
author: Rexcantor64
softdepend: [MultiLanguagePlugin]
description: Test Suite
commands:
    testsuite:
        aliases: [test]
        description: The main command of MultiLanguagePlugin Test Suite.
